"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloProvider } from "@apollo/client";
import client from "./apollo/client/client";
import Header from "./components/header/page";
import { Suspense } from "react";
import Loading from "./components/Loading";
import { FilterProvider } from "./(page)/contextAPI/context/productFilterContect";
import { Provider } from "react-redux";
import store from "./(page)/store/store";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {/* {children} */}
        <ApolloProvider client={client}>
          <Provider store={store}>{children}</Provider>
        </ApolloProvider>
      </body>
    </html>
  );
}
